// Centralized mock data for all neighborhoods on the PlaceDetails page
// Enhanced with more detailed stats and information for all areas
const placesData = {
  whitefield: {
    id: 'whitefield',
    name: 'Whitefield',
    city: 'Bangalore, Karnataka',
    pin: '560066',
    description: "Bangalore's eastern IT corridor with major tech parks, residential townships, and rapid infrastructure growth.",
    tags: ['IT Corridor', 'Tech Parks', 'Residential', 'Growing'],
    image: '/images/neighborhoods/for_desbord.png',
    trend: 'Rising Market',
    population: '350K',
    area: '35.6 sq km',
    updated: '2026-04-15',
    overallScore: 76,
    grade: 'A Grade',
    dimensions: {
      safety: 78,
      environment: 52,
      infrastructure: 76,
      education: 79,
      healthcare: 83,
      lifestyle: 80,
    },
    realEstate: {
      pricePerSqft: '₹9,800',
      oneYearGrowth: '+11.4%',
      fiveYearGrowth: '+65%',
      rentalYield: '4.1% p.a.',
      demandIndex: 84,
      investmentGrade: 'A',
    },
    lifestyle: {
      score: 80,
      malls: 4,
      restaurants: '320+',
      parks: 14,
      entertainment: '78/100',
    },
    highlights: [
      'Home to major IT parks (EPP, ITPL)',
      'Metro connectivity extended',
      'Good social infrastructure',
      'Planned smart city features',
      'Emerging luxury residential hub',
    ],
    watchOut: [
      'Water scarcity issues',
      'Traffic during peak hours',
      'AQI moderate',
      'Construction noise in outer areas',
    ],
    safety: {
      score: 78,
      crimeIndex: 22,
      policeResponse: '14 min',
      streetLighting: '75/100',
      safetyScore: '78/100',
    },
    environment: {
      score: 52,
      aqi: 94,
      aqiStatus: 'Moderate',
      greenCover: '22%',
      waterDry: '4h',
      noiseLevel: '61 dB',
      waterQuality: 'Fair',
    },
    infrastructure: {
      score: 76,
      powerCuts: 2,
      roadQuality: '68/100',
      publicTransport: '71/100',
      broadband: '92 Mbps',
      upcomingProjects: [
        'Purple Line Metro Extension', 
        'Peripheral Ring Road', 
        'EPIP Zone expansion',
        'Kadugodi Multi-modal Hub'
      ],
    },
    education: {
      score: 79,
      schools: 48,
      colleges: 12,
      topRating: '4.3/5',
      avgRating: '3.9/5',
    },
    healthcare: {
      score: 83,
      hospitals: 22,
      clinics: 78,
      nearestHospital: '1.2 km',
      emergency: 'Available',
    },
    mapLocation: { lat: 12.9698, lng: 77.7499, label: 'Whitefield, Bangalore' },
  },
  koramangala: {
    id: 'koramangala',
    name: 'Koramangala',
    city: 'Bangalore, Karnataka',
    pin: '560034',
    description: "Bangalore's premier startup hub and lifestyle destination with vibrant nightlife and world-class coworking spaces.",
    tags: ['Startup Ecosystem', 'Lifestyle', 'Premium', 'Vibrant'],
    image: '/images/neighborhoods/koramangala.png',
    trend: 'Rising Market',
    population: '280K',
    area: '12.4 sq km',
    updated: '2026-04-15',
    overallScore: 89,
    grade: 'A+ Grade',
    dimensions: {
      safety: 82,
      environment: 60,
      infrastructure: 88,
      education: 85,
      healthcare: 90,
      lifestyle: 95,
    },
    realEstate: {
      pricePerSqft: '₹14,500',
      oneYearGrowth: '+9.2%',
      fiveYearGrowth: '+72%',
      rentalYield: '3.8% p.a.',
      demandIndex: 92,
      investmentGrade: 'A+',
    },
    lifestyle: {
      score: 95,
      malls: 6,
      restaurants: '600+',
      parks: 8,
      entertainment: '92/100',
    },
    highlights: [
      'Top startup ecosystem in India',
      'High-end restaurants & cafes',
      'Premium residential options',
      'Excellent metro connectivity',
    ],
    watchOut: [
      'High rental costs',
      'Traffic congestion',
      'Noise pollution at night',
    ],
    safety: {
      score: 82,
      crimeIndex: 18,
      policeResponse: '10 min',
      streetLighting: '85/100',
      safetyScore: '82/100',
    },
    environment: {
      score: 60,
      aqi: 89,
      aqiStatus: 'Moderate',
      greenCover: '18%',
      waterDry: '2h',
      noiseLevel: '68 dB',
      waterQuality: 'Good',
    },
    infrastructure: {
      score: 88,
      powerCuts: 1,
      roadQuality: '80/100',
      publicTransport: '85/100',
      broadband: '150 Mbps',
      upcomingProjects: ['Green Line Metro extension', 'Smart road project'],
    },
    education: {
      score: 85,
      schools: 62,
      colleges: 18,
      topRating: '4.5/5',
      avgRating: '4.1/5',
    },
    healthcare: {
      score: 90,
      hospitals: 28,
      clinics: 95,
      nearestHospital: '0.8 km',
      emergency: 'Available',
    },
    mapLocation: { lat: 12.9352, lng: 77.6245, label: 'Koramangala, Bangalore' },
  },
  bandra: {
    id: 'bandra',
    name: 'Bandra West',
    city: 'Mumbai, Maharashtra',
    pin: '400050',
    description: "Mumbai's most glamorous suburb — blending Bollywood culture, sea-facing promenades, and top-tier dining.",
    tags: ['Business District', 'Sea View', 'Premium', 'Lifestyle'],
    image: '/images/neighborhoods/bandra.png',
    trend: 'Stable Market',
    population: '220K',
    area: '8.2 sq km',
    updated: '2026-04-15',
    overallScore: 84,
    grade: 'A+ Grade',
    dimensions: {
      safety: 75,
      environment: 55,
      infrastructure: 82,
      education: 80,
      healthcare: 86,
      lifestyle: 96,
    },
    realEstate: {
      pricePerSqft: '₹38,000',
      oneYearGrowth: '+5.8%',
      fiveYearGrowth: '+42%',
      rentalYield: '2.9% p.a.',
      demandIndex: 88,
      investmentGrade: 'A+',
    },
    lifestyle: {
      score: 96,
      malls: 8,
      restaurants: '1200+',
      parks: 5,
      entertainment: '96/100',
    },
    highlights: [
      'Iconic Bandstand promenade',
      'Celebrity neighbourhood',
      'Best restaurants in Mumbai',
      'Heritage churches & architecture',
    ],
    watchOut: [
      'Extremely high property prices',
      'Heavy monsoon flooding',
      'Parking issues',
    ],
    safety: {
      score: 75,
      crimeIndex: 28,
      policeResponse: '12 min',
      streetLighting: '80/100',
      safetyScore: '75/100',
    },
    environment: {
      score: 55,
      aqi: 145,
      aqiStatus: 'Unhealthy',
      greenCover: '12%',
      waterDry: '6h',
      noiseLevel: '72 dB',
      waterQuality: 'Fair',
    },
    infrastructure: {
      score: 82,
      powerCuts: 2,
      roadQuality: '72/100',
      publicTransport: '88/100',
      broadband: '120 Mbps',
      upcomingProjects: ['Bandra-Versova Sea Link', 'Metro Line 2A'],
    },
    education: {
      score: 80,
      schools: 38,
      colleges: 14,
      topRating: '4.4/5',
      avgRating: '4.0/5',
    },
    healthcare: {
      score: 86,
      hospitals: 18,
      clinics: 62,
      nearestHospital: '0.5 km',
      emergency: 'Available',
    },
    mapLocation: { lat: 19.0596, lng: 72.8295, label: 'Bandra West, Mumbai' },
  },
  powai: {
    id: 'powai',
    name: 'Powai',
    city: 'Mumbai, Maharashtra',
    pin: '400076',
    description: "Mumbai's planned township built around Powai Lake — home to IIT Bombay and major IT offices.",
    tags: ['Premium', 'IT Mumbai', 'Lakeside', 'Planned Township'],
    image: '/images/neighborhoods/powai.png',
    trend: 'Stable Market',
    population: '180K',
    area: '18.5 sq km',
    updated: '2026-04-15',
    overallScore: 88,
    grade: 'A Grade',
    dimensions: {
      safety: 80,
      environment: 65,
      infrastructure: 85,
      education: 90,
      healthcare: 84,
      lifestyle: 82,
    },
    realEstate: {
      pricePerSqft: '₹22,000',
      oneYearGrowth: '+6.9%',
      fiveYearGrowth: '+48%',
      rentalYield: '3.2% p.a.',
      demandIndex: 86,
      investmentGrade: 'A',
    },
    lifestyle: {
      score: 82,
      malls: 3,
      restaurants: '400+',
      parks: 10,
      entertainment: '80/100',
    },
    highlights: [
      'IIT Bombay campus nearby',
      'Powai Lake waterfront',
      'Major IT companies HQs',
      'Planned infrastructure',
    ],
    watchOut: [
      'High traffic on LBS Marg',
      'Water supply issues in summer',
      'Limited public transport',
    ],
    safety: {
      score: 80,
      crimeIndex: 20,
      policeResponse: '11 min',
      streetLighting: '82/100',
      safetyScore: '80/100',
    },
    environment: {
      score: 65,
      aqi: 118,
      aqiStatus: 'Unhealthy',
      greenCover: '28%',
      waterDry: '4h',
      noiseLevel: '64 dB',
      waterQuality: 'Good',
    },
    infrastructure: {
      score: 85,
      powerCuts: 1,
      roadQuality: '78/100',
      publicTransport: '74/100',
      broadband: '130 Mbps',
      upcomingProjects: ['Metro Line 6', 'Eastern Freeway extension'],
    },
    education: {
      score: 90,
      schools: 42,
      colleges: 20,
      topRating: '4.6/5',
      avgRating: '4.2/5',
    },
    healthcare: {
      score: 84,
      hospitals: 16,
      clinics: 58,
      nearestHospital: '1.0 km',
      emergency: 'Available',
    },
    mapLocation: { lat: 19.1176, lng: 72.9060, label: 'Powai, Mumbai' },
  },
};

// Helper: create a slug from a neighborhood name
export const getPlaceSlug = (name) => {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '').trim();
};

export default placesData;
